### ISSUE TITLE
yesod-auth-basic-0.1.0.2 build failure with yesod-1.3

### ISSUE THREAD

**Issue by DanBurton** [creichert/yesod-auth-basic#2]
As seen on the Stackage build server:

```
Building library for yesod-auth-basic-0.1.0.2..
[1 of 1] Compiling Yesod.Auth.Http.Basic ( Yesod/Auth/Http/Basic.hs, dist/build/Yesod/Auth/Http/Basic.o )

Yesod/Auth/Http/Basic.hs:117:32: error:
    Not in scope: type constructor or class ‘MonadBaseControl’
    |
117 |   :: (MonadIO m, MonadThrow m, MonadBaseControl IO m)
    |                                ^^^^^^^^^^^^^^^^

Yesod/Auth/Http/Basic.hs:127:32: error:
    Not in scope: type constructor or class ‘MonadBaseControl’
    |
127 |   :: (MonadIO m, MonadThrow m, MonadBaseControl IO m)
    |                                ^^^^^^^^^^^^^^^^
```

I was able to reproduce locally like so:

```bash
stack unpack yesod-auth-basic-0.1.0.2 && cd yesod-auth-basic-0.1.0.2
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- yesod-1.6.0
- conduit-1.3.0
- conduit-extra-1.3.0
- yesod-core-1.6.2
- yesod-form-1.6.1
- yesod-persistent-1.6.0
- resourcet-1.2.0
- persistent-2.8.0
```
